### ISSUE TITLE
Star This Repo

### ISSUE THREAD

**Issue by mubaris** [gostudent/Algorithms#12]
Post Screenshots

**Comment by brain-sick** [comment]
![go2](https://user-images.githubusercontent.com/34164978/34838556-82b81dc0-f724-11e7-818a-c660c14c468c.png)

**Comment by amriteshbhaskar** [comment]
![algorithm](https://user-images.githubusercontent.com/34058250/34838877-ba67f636-f725-11e7-884a-0e1b18b09bab.png)

**Comment by GOVINDDIXIT** [comment]
![captureal](https://user-images.githubusercontent.com/32304546/34839122-91791718-f726-11e7-85bf-5e8c8327a063.PNG)

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34839411-82a26220-f727-11e7-9c11-fee065c33cea.png)

**Comment by ananya-agrawal** [comment]
![a](https://user-images.githubusercontent.com/33188930/34839416-87327e9c-f727-11e7-89e3-5bac79194dc9.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-12 gostudent algorithms](https://user-images.githubusercontent.com/28799332/34840695-c90fbb78-f72b-11e7-9eb1-874726aa9a6d.png)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/34840854-5301e3e2-f72c-11e7-9464-81a0e8fcdc86.png)

**Comment by rahulkumaran** [comment]
![screenshot from 2018-01-12 00-10-46](https://user-images.githubusercontent.com/26206171/34841094-133bf454-f72d-11e7-8167-b0715d6ee8f6.png)

**Comment by ProBeta1** [comment]
![screenshot-2018-1-12 gostudent algorithms](https://user-images.githubusercontent.com/33081197/34844131-73703516-f736-11e7-818e-0ddedd19226a.png)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34846314-c00ee032-f73d-11e7-8f62-d244582b430d.png)

**Comment by ShiningSaurabh** [comment]
![capture](https://user-images.githubusercontent.com/34839782/34847612-f50fa358-f741-11e7-8bf2-1840d200051e.PNG)

**Comment by Tlazypanda** [comment]
![image](https://user-images.githubusercontent.com/33183263/34866153-89a02a56-f7a1-11e7-855b-0c883503ba0d.png)

**Comment by vvvinamer** [comment]
![screenshot 35](https://user-images.githubusercontent.com/35339278/34868783-ed2b4354-f7aa-11e7-9310-a5a2b04e9731.png)

**Comment by AlphaCholera** [comment]
![screenshot from 2018-01-12 21-15-11](https://user-images.githubusercontent.com/33174671/34870276-9c78b78e-f7af-11e7-8113-9e967cc24a33.png)

**Comment by maverick0004** [comment]
![screenshot from 2018-01-12 16-53-48](https://user-images.githubusercontent.com/33194760/34872977-36d5140e-f7b9-11e7-9306-7afdebafb012.png)

**Comment by nityanandagohain** [comment]
![screenshot from 2018-01-12 18-01-12](https://user-images.githubusercontent.com/26831659/34875324-cb096d4c-f7c2-11e7-94ac-af83529e1926.png)
